// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon/micheckhash.png
var resourceMicheckhashPngData []byte
var resourceMicheckhashPng = &fyne.StaticResource{
	StaticName:    "icon/micheckhash.png",
	StaticContent: resourceMicheckhashPngData,
}